# Generated by Django 5.2.7 on 2025-11-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_users', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(default='temp', max_length=254, null=True)),
            ],
        ),
    ]
